name: replay_classification
channels:
- conda-forge
- defaults
- ioam
- edeno
dependencies:
- "python>=3.6"
- setuptools
- numpy
- scipy
- pandas
- xarray
- statsmodels
- regularized_glm
- matplotlib
- seaborn
- scikit-learn
- patsy
- pytest
- jupyter
- coveralls
- pytest-cov
- numba
- holoviews
- bokeh
- tqdm
